name: Go
on: [push]
env:
  VERSION: 0.1

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Commit tagger
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ env.VERSION }}.${{ github.run_number }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: ~1.8.2
        args: --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Rename
      run: |
        mv dist/bilibili-live-stream_windows_arm64/bilibili-live-stream.exe bilibili-live-stream-windows_arm64.exe
        mv dist/bilibili-live-stream_windows_amd64_v1/bilibili-live-stream.exe bilibili-live-stream-windows_amd64.exe
        mv dist/bilibili-live-stream_darwin_arm64/bilibili-live-stream bilibili-live-stream-darwin_arm64
        mv dist/bilibili-live-stream_darwin_amd64_v1/bilibili-live-stream bilibili-live-stream-darwin_amd64
        mv dist/bilibili-live-stream_linux_arm64/bilibili-live-stream bilibili-live-stream-linux_arm64
        mv dist/bilibili-live-stream_linux_amd64_v1/bilibili-live-stream bilibili-live-stream-linux_amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        generate_release_notes: true
        name: v${{ env.VERSION }}.${{ github.run_number }}
        tag_name: ${{ env.VERSION }}.${{ github.run_number }}
        files: |
          bilibili-live-stream-windows_arm64.exe
          bilibili-live-stream-windows_amd64.exe
          bilibili-live-stream-darwin_arm64
          bilibili-live-stream-darwin_amd64
          bilibili-live-stream-linux_arm64
          bilibili-live-stream-linux_amd64
